site_name: Analiza Dynamiki Zmian - Projekt SWPZ
site_description: Instrukcja wyznaczania indeksów łańcuchowych dla zespołu

theme:
  name: material # Wykorzystanie szablonu innego niż domyślny
  palette:
    - scheme: default
      primary: green # Modyfikacja istniejącego szablonu
      accent: light-green
  features:
    - navigation.sections

nav:
  - Strona główna: index.md
  - Zespół projektowy: autorzy.md
  - Podstawa teoretyczna: teoria.md
  - Architektura systemu: architektura.md
  - Przykłady i kod: przyklady.md
  - Wyniki i testowanie: testowanie.md